# This is a basic workflow to help you get started with Actions

name: CI_ShanviStore

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      - self-hosted
      - label-1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Docker login
        run: |
          docker login -u ${{ secrets.NEXUS_USERNAME }} -p ${{ secrets.NEXUS_PASSWORD }} ${{ vars.NEXUS_REPO }}
      - name: Extract Git hash and date
        id: vars
        run: |
          GIT_HASH=$(git rev-parse --short=8 HEAD) 
          TAG_VERSION=0.0.99
          echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run Building Docker image
        run: |
          cd $GITHUB_WORKSPACE/build
          docker build -t shanvistore .
          docker tag shanvistore:latest ${{ vars.NEXUS_REPO }}/shanvistore:${{ env.TAG_VERSION }}-${{ env.GIT_HASH }}
      - name: Run Pushing Docker image
        run: |
          docker push ${{ vars.NEXUS_REPO }}/shanvistore:${{ env.TAG_VERSION }}-${{ env.GIT_HASH }}
      - name: Update Version 
        run: |
          sed -i "s/tag: .*/tag: ${{ env.TAG_VERSION }}-${{ env.GIT_HASH }}/" $GITHUB_WORKSPACE/helm/shanvistore/values.yaml
      - name: Helm package & Push to Nexus Repo
        run: |
          helm package -d $GITHUB_WORKSPACE/helm/ $GITHUB_WORKSPACE/helm/shanvistore --version 1.0.0-${{ env.TAG_VERSION }}-${{ env.GIT_HASH }}
          curl -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} http://192.168.56.111:8081/repository/valay-helm/ --upload-file $GITHUB_WORKSPACE/helm/shanvistore-1.0.0-${{ env.TAG_VERSION }}-${{ env.GIT_HASH }}.tgz -v
